#ifndef Engine_Enum_h__
#define Engine_Enum_h__

namespace Engine
{
	enum WINMODE { MODE_FULL, MODE_WIN };

	// Dynamic 컴포넌트 경우 매 프레임마다 갱신해야하는 컴포넌트 집단
	enum COMPONENTID { ID_DYNAMIC, ID_STATIC, ID_END };

	enum INFO {	INFO_RIGHT, INFO_UP, INFO_LOOK, INFO_POS, INFO_END };
	enum ROTATION { ROT_X, ROT_Y, ROT_Z, ROT_END };

	enum TEXTUREID { TEX_NORMAL, TEX_CUBE, TEX_END };

	enum RENDERID { RENDER_PRIORITY, RENDER_NONALPHA, RENDER_ALPHA, RENDER_ALPHA_SORTING, RENDER_UI, RENDER_PARTICLES, RENDER_NONE, RENDER_END };

	enum MOUSEKEYSTATE { DIM_LB, DIM_RB, DIM_MB, DIM_END };
	enum MOUSEMOVESTATE {	DIMS_X, DIMS_Y, DIMS_Z, DIMS_END };

	enum PLACEMENT_TYPE { OBJECT, MONSTER, BOSS, ITEM };

	// ALLPLAY : 끝까지 재생돼야하는 이펙트음
	// STOPSUDDEN : 중간에 끊기더라도 끊어내야하는애들
	enum CHANNEL_ID {
		SOUND_EFFECT_PLAYER_ALLPLAY, SOUND_EFFECT_PLAYER_STOPSUDDEN, SOUND_EFFECT_PLAYER_LOOP,
		SOUND_EFFECT_MON_ALLPLAY, SOUND_EFFECT_MON_STOPSUDDEN,
		SOUND_EFFECT_MON_ALLPLAY_SUB, SOUND_EFFECT_MON_STOPSUDDEN_SUB,
		SOUND_EFFECT_OBJ_ALLPLAY, SOUND_EFFECT_OBJ_STOPSUDDEN,
		SOUND_EFFECT_ITEM_ALLPLAY, SOUND_EFFECT_ITEM_STOPSUDDEN,
		SOUND_EFFECT_ETC_ALLPLAY, SOUND_EFFECT_ETC_STOPSUDDEN, SOUND_EFFECT, SOUND_BGM, MAXCHANNEL
	};

	enum OBJECT_TYPE { POOP, CAMPFIRE, SPIKE, SHELL_GAME, SLOT_MC, SHOP, OBSTACLE, OBSTACLE_X, OBSTACLE_Z, DEVIL, OBJECT_TYPE_END };
	enum MONSTER_TYPE {FLY, ATTACK_FLY, PACER, LEAPER, SQUIRT, DIP, DOPLE, CHARGER, MONSTER_TYPE_END };
	enum BOSS_TYPE { MONSTRO, MOM, MOM_PARTS, NONE_BOSS };
	enum ITEM_TYPE 
	{	
		BRIM, EPIC, SAD_ONION, TRINKET,
		COIN, HEART, HEART_HALF, PILL, ITEM_NONE
	};

	enum SHADER_PASS_ID
	{
		SHADER_DEFAULT, SHADER_WHITE, SHADER_ALPHA, SHADER_COLOR
	};

}
#endif // Engine_Enum_h__
